// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfUCJlDbjum29gSx9KYx1oYFWuYGSu34E',
    appId: '1:269764048781:web:d96f9bc6db8f7d102fafc4',
    messagingSenderId: '269764048781',
    projectId: 'chauthainhan-devapps',
    authDomain: 'chauthainhan-devapps.firebaseapp.com',
    storageBucket: 'chauthainhan-devapps.firebasestorage.app',
    measurementId: 'G-F5D5DYZRKG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0KsIIxv3y7aHWKsy7pVtEiGakfNwKTqs',
    appId: '1:269764048781:android:ee4d5cf035fc32132fafc4',
    messagingSenderId: '269764048781',
    projectId: 'chauthainhan-devapps',
    storageBucket: 'chauthainhan-devapps.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJRQyMHSD3gGgdr1XTEjLY-AzrwzHI4vg',
    appId: '1:269764048781:ios:e7ce1f71166beb452fafc4',
    messagingSenderId: '269764048781',
    projectId: 'chauthainhan-devapps',
    storageBucket: 'chauthainhan-devapps.firebasestorage.app',
    iosBundleId: 'com.nhanchaukp.fcode.pos',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJRQyMHSD3gGgdr1XTEjLY-AzrwzHI4vg',
    appId: '1:269764048781:ios:e7ce1f71166beb452fafc4',
    messagingSenderId: '269764048781',
    projectId: 'chauthainhan-devapps',
    storageBucket: 'chauthainhan-devapps.firebasestorage.app',
    iosBundleId: 'com.nhanchaukp.fcode.pos',
  );
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfUCJlDbjum29gSx9KYx1oYFWuYGSu34E',
    appId: '1:269764048781:web:d96f9bc6db8f7d102fafc4',
    messagingSenderId: '269764048781',
    projectId: 'chauthainhan-devapps',
    authDomain: 'chauthainhan-devapps.firebaseapp.com',
    storageBucket: 'chauthainhan-devapps.firebasestorage.app',
    measurementId: 'G-F5D5DYZRKG',
  );
}
